/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package book.manager.app

import book.manager.utilities.StringUtils
import io.micronaut.runtime.Micronaut
import io.swagger.v3.oas.annotations.OpenAPIDefinition
import io.swagger.v3.oas.annotations.info.Info

@OpenAPIDefinition(
    info = Info(
        title = "demo",
        version = "0.0"
    )
)
object Api {
}

fun main(args: Array<String>) {
    Micronaut.build()
        .args(*args)
        .packages("book.manager")
        .start()
}

